# frozen_string_literal: true

source 'https://rubygems.org'

gem 'auth', github: 'alexfalkowski/auth', tag: 'v1.64.1', glob: 'test/*.gemspec'
gem 'aws-sdk-s3'
gem 'aws-sdk-ssm'
gem 'cucumber'
gem 'nonnative'
gem 'rspec-expectations'
gem 'rspec-wait'
gem 'rubocop'
gem 'ruby-lsp'
gem 'toml-rb'
gem 'vault'
