# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-sdk-s3'
gem 'aws-sdk-ssm'
gem 'cucumber'
gem 'nonnative'
gem 'rspec-expectations'
gem 'rspec-wait'
gem 'rubocop'
gem 'solargraph'
gem 'toml-rb'
gem 'vault'
