version: 2.1

jobs:
  build:
    docker:
      - image: alexfalkowski/go:1.18
      - image: redis
      - image: vault
        environment:
          VAULT_DEV_ROOT_TOKEN_ID: vault-plaintext-root-token
    steps:
      - checkout
      - run: dockerize -wait tcp://localhost:6379 -wait tcp://localhost:8200 -timeout 1m
      - run: make dep
      - run: make lint
      - run: make features
      - run: make goveralls
      - store_artifacts:
          path: test/reports
  release:
    docker:
      - image: alexfalkowski/release:2.0
    steps:
      - checkout
      - run: release

workflows:
  konfig:
    jobs:
      - build
      - release:
          context: gh
          requires:
            - build
          filters:
            branches:
              only: master
