version: 2.1

jobs:
  build:
    docker:
      - image: alexfalkowski/go:1.21-ruby
      - image: localstack/localstack:latest
        environment:
          SERVICES: s3,ssm
      - image: hashicorp/vault:latest
        environment:
          VAULT_DEV_ROOT_TOKEN_ID: vault-plaintext-root-token
    working_directory: ~/konfig
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: dockerize -wait tcp://localhost:8200 -wait tcp://localhost:4566 -timeout 1m
      - run: make dep
      - run: make lint
      - run: make proto-breaking
      - run: make sec
      - run: make features
      - run: make goveralls
      - store_artifacts:
          path: test/reports
    resource_class: large
  release:
    docker:
      - image: alexfalkowski/release:3.1
    working_directory: ~/konfig
    steps:
      - checkout
      - run: release
    resource_class: large
  docker:
    docker:
      - image: alexfalkowski/go:1.21-ruby
    working_directory: ~/konfig
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make docker
    resource_class: large

workflows:
  konfig:
    jobs:
      - build
      - release:
          context: gh
          requires:
            - build
          filters:
            branches:
              only: master
      - docker:
          context: docker
          requires:
            - release
          filters:
            branches:
              only: master
