// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: konfig/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config for a specific application.
type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   string                 `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Continent     string                 `protobuf:"bytes,4,opt,name=continent,proto3" json:"continent,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Command       string                 `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`
	Kind          string                 `protobuf:"bytes,7,opt,name=kind,proto3" json:"kind,omitempty"`
	Data          []byte                 `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_konfig_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_konfig_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_konfig_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *Config) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Config) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Config) GetContinent() string {
	if x != nil {
		return x.Continent
	}
	return ""
}

func (x *Config) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Config) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Config) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Config) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetConfigRequest for a specific application.
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   string                 `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Continent     string                 `protobuf:"bytes,4,opt,name=continent,proto3" json:"continent,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Command       string                 `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`
	Kind          string                 `protobuf:"bytes,7,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_konfig_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_konfig_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_konfig_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigRequest) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *GetConfigRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetConfigRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *GetConfigRequest) GetContinent() string {
	if x != nil {
		return x.Continent
	}
	return ""
}

func (x *GetConfigRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetConfigRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetConfigRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// GetConfigResponse for a specific application.
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          map[string]string      `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Config        *Config                `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_konfig_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_konfig_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_konfig_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetConfigResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// GetSecretsRequest a map of name and secret.
type GetSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       map[string]string      `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsRequest) Reset() {
	*x = GetSecretsRequest{}
	mi := &file_konfig_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsRequest) ProtoMessage() {}

func (x *GetSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_konfig_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsRequest.ProtoReflect.Descriptor instead.
func (*GetSecretsRequest) Descriptor() ([]byte, []int) {
	return file_konfig_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretsRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// GetSecretsResponse a map of meta and secrets.
type GetSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          map[string]string      `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Secrets       map[string][]byte      `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsResponse) Reset() {
	*x = GetSecretsResponse{}
	mi := &file_konfig_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsResponse) ProtoMessage() {}

func (x *GetSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_konfig_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsResponse.ProtoReflect.Descriptor instead.
func (*GetSecretsResponse) Descriptor() ([]byte, []int) {
	return file_konfig_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetSecretsResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetSecretsResponse) GetSecrets() map[string][]byte {
	if x != nil {
		return x.Secrets
	}
	return nil
}

var File_konfig_v1_service_proto protoreflect.FileDescriptor

const file_konfig_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x17konfig/v1/service.proto\x12\tkonfig.v1\"\xe0\x01\n" +
	"\x06Config\x12 \n" +
	"\vapplication\x18\x01 \x01(\tR\vapplication\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x1c\n" +
	"\tcontinent\x18\x04 \x01(\tR\tcontinent\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x18\n" +
	"\acommand\x18\x06 \x01(\tR\acommand\x12\x12\n" +
	"\x04kind\x18\a \x01(\tR\x04kind\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04data\"\xd6\x01\n" +
	"\x10GetConfigRequest\x12 \n" +
	"\vapplication\x18\x01 \x01(\tR\vapplication\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x1c\n" +
	"\tcontinent\x18\x04 \x01(\tR\tcontinent\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x18\n" +
	"\acommand\x18\x06 \x01(\tR\acommand\x12\x12\n" +
	"\x04kind\x18\a \x01(\tR\x04kind\"\xb3\x01\n" +
	"\x11GetConfigResponse\x12:\n" +
	"\x04meta\x18\x01 \x03(\v2&.konfig.v1.GetConfigResponse.MetaEntryR\x04meta\x12)\n" +
	"\x06config\x18\x02 \x01(\v2\x11.konfig.v1.ConfigR\x06config\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\x11GetSecretsRequest\x12C\n" +
	"\asecrets\x18\x01 \x03(\v2).konfig.v1.GetSecretsRequest.SecretsEntryR\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x02\n" +
	"\x12GetSecretsResponse\x12;\n" +
	"\x04meta\x18\x01 \x03(\v2'.konfig.v1.GetSecretsResponse.MetaEntryR\x04meta\x12D\n" +
	"\asecrets\x18\x02 \x03(\v2*.konfig.v1.GetSecretsResponse.SecretsEntryR\asecrets\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x012\xa0\x01\n" +
	"\aService\x12H\n" +
	"\tGetConfig\x12\x1b.konfig.v1.GetConfigRequest\x1a\x1c.konfig.v1.GetConfigResponse\"\x00\x12K\n" +
	"\n" +
	"GetSecrets\x12\x1c.konfig.v1.GetSecretsRequest\x1a\x1d.konfig.v1.GetSecretsResponse\"\x00B<Z-github.com/alexfalkowski/konfig/api/konfig/v1\xea\x02\n" +
	"Konfig::V1b\x06proto3"

var (
	file_konfig_v1_service_proto_rawDescOnce sync.Once
	file_konfig_v1_service_proto_rawDescData []byte
)

func file_konfig_v1_service_proto_rawDescGZIP() []byte {
	file_konfig_v1_service_proto_rawDescOnce.Do(func() {
		file_konfig_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_konfig_v1_service_proto_rawDesc), len(file_konfig_v1_service_proto_rawDesc)))
	})
	return file_konfig_v1_service_proto_rawDescData
}

var file_konfig_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_konfig_v1_service_proto_goTypes = []any{
	(*Config)(nil),             // 0: konfig.v1.Config
	(*GetConfigRequest)(nil),   // 1: konfig.v1.GetConfigRequest
	(*GetConfigResponse)(nil),  // 2: konfig.v1.GetConfigResponse
	(*GetSecretsRequest)(nil),  // 3: konfig.v1.GetSecretsRequest
	(*GetSecretsResponse)(nil), // 4: konfig.v1.GetSecretsResponse
	nil,                        // 5: konfig.v1.GetConfigResponse.MetaEntry
	nil,                        // 6: konfig.v1.GetSecretsRequest.SecretsEntry
	nil,                        // 7: konfig.v1.GetSecretsResponse.MetaEntry
	nil,                        // 8: konfig.v1.GetSecretsResponse.SecretsEntry
}
var file_konfig_v1_service_proto_depIdxs = []int32{
	5, // 0: konfig.v1.GetConfigResponse.meta:type_name -> konfig.v1.GetConfigResponse.MetaEntry
	0, // 1: konfig.v1.GetConfigResponse.config:type_name -> konfig.v1.Config
	6, // 2: konfig.v1.GetSecretsRequest.secrets:type_name -> konfig.v1.GetSecretsRequest.SecretsEntry
	7, // 3: konfig.v1.GetSecretsResponse.meta:type_name -> konfig.v1.GetSecretsResponse.MetaEntry
	8, // 4: konfig.v1.GetSecretsResponse.secrets:type_name -> konfig.v1.GetSecretsResponse.SecretsEntry
	1, // 5: konfig.v1.Service.GetConfig:input_type -> konfig.v1.GetConfigRequest
	3, // 6: konfig.v1.Service.GetSecrets:input_type -> konfig.v1.GetSecretsRequest
	2, // 7: konfig.v1.Service.GetConfig:output_type -> konfig.v1.GetConfigResponse
	4, // 8: konfig.v1.Service.GetSecrets:output_type -> konfig.v1.GetSecretsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_konfig_v1_service_proto_init() }
func file_konfig_v1_service_proto_init() {
	if File_konfig_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_konfig_v1_service_proto_rawDesc), len(file_konfig_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_konfig_v1_service_proto_goTypes,
		DependencyIndexes: file_konfig_v1_service_proto_depIdxs,
		MessageInfos:      file_konfig_v1_service_proto_msgTypes,
	}.Build()
	File_konfig_v1_service_proto = out.File
	file_konfig_v1_service_proto_goTypes = nil
	file_konfig_v1_service_proto_depIdxs = nil
}
