# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: konfig/v1/service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("konfig/v1/service.proto", :syntax => :proto3) do
    add_message "konfig.v1.Config" do
      optional :application, :string, 1, json_name: "application"
      optional :version, :string, 2, json_name: "version"
      optional :environment, :string, 3, json_name: "environment"
      optional :cluster, :string, 4, json_name: "cluster"
      optional :command, :string, 5, json_name: "command"
      optional :content_type, :string, 6, json_name: "contentType"
      optional :data, :bytes, 7, json_name: "data"
    end
    add_message "konfig.v1.GetConfigRequest" do
      optional :application, :string, 1, json_name: "application"
      optional :version, :string, 2, json_name: "version"
      optional :environment, :string, 3, json_name: "environment"
      optional :cluster, :string, 4, json_name: "cluster"
      optional :command, :string, 5, json_name: "command"
    end
    add_message "konfig.v1.GetConfigResponse" do
      optional :config, :message, 1, "konfig.v1.Config", json_name: "config"
    end
  end
end

module Konfig
  module V1
    Config = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("konfig.v1.Config").msgclass
    GetConfigRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("konfig.v1.GetConfigRequest").msgclass
    GetConfigResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("konfig.v1.GetConfigResponse").msgclass
  end
end
