#!/usr/bin/env bash

set -e

# Update all the aws deps.
make module=github.com/aws/aws-sdk-go-v2/service/ssm go-update-dep
make module=github.com/aws/aws-sdk-go-v2/service/s3 go-update-dep
make module=github.com/aws/aws-sdk-go-v2/config go-update-dep

# Update all tghe ruby deps.
make ruby-update-all-dep
