#!/usr/bin/env bash

set -e

go install -mod=mod github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
go install -mod=mod github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
go install -mod=mod google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install -mod=mod google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
