#!/usr/bin/env bash

set -e

# Generate API.
protoc -I api --go_out=server/v1/transport/grpc --go_opt=paths=source_relative \
    --go-grpc_out=server/v1/transport/grpc --go-grpc_opt=paths=source_relative \
    --grpc-gateway_out=server/v1/transport/grpc --grpc-gateway_opt=paths=source_relative \
    api/konfig.v1.proto
