#!/usr/bin/env bash

set -e

# Generate API.
protoc -I api --go_out=api --go_opt=paths=source_relative \
    --go-grpc_out=api --go-grpc_opt=paths=source_relative \
    --grpc-gateway_out=api --grpc-gateway_opt=paths=source_relative \
    api/konfig/v1/service.proto
